-- H2 兼容建表脚本（MySQL 兼容模式）
-- 用于集成测试，覆盖核心业务表

CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255),
    password VARCHAR(255),
    nickname VARCHAR(255),
    email VARCHAR(255),
    phone VARCHAR(255),
    avatar VARCHAR(500),
    user_type VARCHAR(50) DEFAULT 'GUEST',
    guest_expire_at TIMESTAMP NULL,
    merged_into BIGINT NULL,
    wechat_openid VARCHAR(255),
    wechat_unionid VARCHAR(255),
    wechat_nickname VARCHAR(255),
    wechat_avatar VARCHAR(500),
    wechat_bind_status INT DEFAULT 0,
    wechat_bind_time TIMESTAMP NULL,
    gender INT DEFAULT 0,
    status INT DEFAULT 1,
    role VARCHAR(100) DEFAULT 'USER',
    dept_id BIGINT NULL,
    remark VARCHAR(500),
    last_login_time TIMESTAMP NULL,
    last_login_ip VARCHAR(50),
    create_by VARCHAR(100),
    update_by VARCHAR(100),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    delete_flag INT DEFAULT 0,
    version INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS user_body (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    gender INT,
    age INT,
    height DOUBLE,
    weight DOUBLE,
    target_weight DOUBLE,
    activity_level INT,
    activity_factor DOUBLE,
    deficit INT,
    cfc DOUBLE,
    mode INT DEFAULT 1,
    bmr INT,
    tdee INT,
    target_kcal INT,
    target_carb DOUBLE,
    target_protein DOUBLE,
    target_fat DOUBLE,
    is_adjusted INT DEFAULT 0,
    trigger_weight DOUBLE,
    status INT DEFAULT 1,
    create_by VARCHAR(100),
    update_by VARCHAR(100),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    delete_flag INT DEFAULT 0,
    version INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS diet_records (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    record_date DATE NOT NULL,
    meal_type INT NOT NULL,
    source INT DEFAULT 1,
    food_id BIGINT,
    food_name VARCHAR(255),
    carb_100g DECIMAL(10,2),
    protein_100g DECIMAL(10,2),
    fat_100g DECIMAL(10,2),
    kcal_100g INT,
    amount_g DOUBLE,
    carb_g DOUBLE,
    protein_g DOUBLE,
    fat_g DOUBLE,
    kcal INT,
    remark VARCHAR(500),
    status INT DEFAULT 1,
    create_by VARCHAR(100),
    update_by VARCHAR(100),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    delete_flag INT DEFAULT 0,
    version INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS weight_record (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    record_date DATE NOT NULL,
    weight DOUBLE NOT NULL,
    status INT DEFAULT 1,
    create_by VARCHAR(100),
    update_by VARCHAR(100),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    delete_flag INT DEFAULT 0,
    version INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS foods (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(50),
    category_code VARCHAR(50),
    category_name VARCHAR(100),
    name VARCHAR(255),
    alias VARCHAR(255),
    carb DECIMAL(10,2),
    protein DECIMAL(10,2),
    fat DECIMAL(10,2),
    kcal INT,
    serving DECIMAL(10,2),
    source INT DEFAULT 1,
    user_id BIGINT,
    status INT DEFAULT 1,
    create_by VARCHAR(100),
    update_by VARCHAR(100),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    delete_flag INT DEFAULT 0,
    version INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS food_images (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    food_code VARCHAR(50),
    object_key VARCHAR(255) NOT NULL,
    url VARCHAR(512),
    source INT DEFAULT 1,
    status INT DEFAULT 1,
    create_by VARCHAR(100),
    update_by VARCHAR(100),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    delete_flag INT DEFAULT 0,
    version INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS project_config (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    config_key VARCHAR(100) NOT NULL,
    config_value CLOB,
    value_type INT NOT NULL,
    remark VARCHAR(255),
    status INT DEFAULT 1,
    create_by VARCHAR(100),
    update_by VARCHAR(100),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    delete_flag INT DEFAULT 0,
    version INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS user_reminders (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    master_switch INT DEFAULT 0,
    breakfast_switch INT DEFAULT 0,
    breakfast_time VARCHAR(10),
    lunch_switch INT DEFAULT 0,
    lunch_time VARCHAR(10),
    dinner_switch INT DEFAULT 0,
    dinner_time VARCHAR(10),
    subscribe_credit INT DEFAULT 0,
    status INT DEFAULT 1,
    create_by VARCHAR(100),
    update_by VARCHAR(100),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    delete_flag INT DEFAULT 0,
    version INT DEFAULT 0
);